config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth"
  resources :users
  resources :favorites do
    collection do
      post "add_to_favorite"
      delete "remove_from_favorite"
    end
  end
  resources :questions do
    collection do
    end
    member do
      post "answer"
    end
  end

  resources :answers do
    member do
      post "upvote"
      post "downvote"
    end
  end

  get "myself" => "users#myself", as: :myself

  root to: "questions#index"

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  validates_presence_of :title
  field :body, type: String
  field :clicks, type: Integer, default: 0


  field :answers_count, type: Integer, default: 0
  field :total_votes, type: Integer, default: 0

  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: "User"
  validates_presence_of :author


  def self.hottestq
    all.desc(:clicks, :answers_count, :total_votes, :created_at)
  end

  def self.search(search)
    # where("title like ?", "%#{search}%")
    where(title: "#{search}")

    # if search
    #   find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    # else
    #   find(:all)
    # end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :answer]
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /questions
  # GET /questions.json
  def index
    #@questions = Question.all.sort{|a1, a2| a2.total_votes <=> a1.total_votes}.page params[:page]
    
    #@questions = @questions.sort{|a1, a2| a2.total_votes <=> a1.total_votes}
    if params[:search]
      @questions = Question.search(params[:search]).page params[:questions_page]
    else
      @questions = Question.all.desc(:total_votes, :answers_count, :created_at).page params[:questions_page]
    end

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question.clicks+=1
    @question.save
  end

  def answer
    @question.answers.create(body: params[:answer][:body], author: current_user)
    answer = @question.answers.to_a[@question.answers.length - 1]
    redirect_to question_path(answer.question.id, page: (answer.question.answers.desc(:votes, :created_at).to_a.index(answer) / Answer.default_per_page + 1), anchor: answer.id), notice: 'Answer was successfully created'
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.author = current_user
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="btn-group">
  <% if params[:index].to_i == 0 %>
    <%= link_to 'Hottest Questions', questions_path(index: 0), class: "btn btn-default active", autofocus: true %>
    <%= link_to 'Hottest Answers', questions_path(index: 1), class: "btn btn-default" %>
  <% elsif params[:index].to_i == 1 %>
    <%= link_to 'Hottest Questions', questions_path(index: 0), class: "btn btn-default", autofocus: true %>
    <%= link_to 'Hottest Answers', questions_path(index: 1), class: "btn btn-default active" %>
  <% end -%>
  <%= link_to 'New Question', new_question_path, class: "btn btn-default" %>
</div>

<%= form_tag(questions_path, method: "get", :class => 'search_form') do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<div class="btn-group pull-right">
  <% if current_user.admin? %>
    <%= link_to 'Manage All Users', users_path, class: "btn btn-default" %>
  <% end -%>
  <%= link_to 'My Home Page', myself_path(index: 0), class: "btn btn-default" %>
</div>

<br>
<br />





<% if params[:index].to_i == 0 %>
  <h1>Hottest Questions</h1>
  <hr />
  <div class="hottest_questions">
    <% @questions.each do |question| %>
      <div>
        <h5><strong><%= link_to "#{question.title}", question_path(question) %></strong> ASKED BY<%= question.author.email %></h5>
        <p><%= question.body %></p>
        <%= question.answers_count %> answers | 
        <%= question.total_votes %> total votes
        <br /><hr />
      </div>
    <% end -%>
  </div>

  <%= paginate @questions, :param_name => "questions_page" %>
<% elsif params[:index].to_i == 1 %>
  <h1>Hottest Answers</h1>
  <hr />
  <div class="hottest_answers">
    <% answers = Answer.all.desc(:votes, :created_at).page params[:answers_page] %>
    <% answers.each do |answer| %>
      <div>
        <h5><strong><%= link_to "#{answer.question.title}", question_path(answer.question) %></strong></h5>
          <%= answer.votes %> votes <br /><br />
          <p><%= link_to "#{answer.body}", question_path(answer.question, page: (answer.question.answers.desc(:votes, :created_at).to_a.index(answer) / Answer.default_per_page + 1), anchor: answer.id) %></p>
          <hr />
      </div>
    <% end -%>
  </div>
  <%= paginate answers, :param_name => "answers_page" %>
<% end -%>

app/views/questions/new.html.erb
<%= link_to 'Back to Main Page', questions_path, class: "btn btn-default pull-right" %>

<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="pull-right">
	<%= link_to 'Edit', edit_question_path(@question), class: "btn btn-default" %> |
	<%= link_to 'Back to Main Page', questions_path, class: "btn btn-default" %>
</div>

<% form_tag questions_path do %>
  <p>
    <%= text_field_tag :search %>
    <%= submit_tag "Search" %>
  </p>
<% end %>

<h3><%= @question.title %></h3>
<p>ASKED BY<%= @question.author.email %></p>
<p>clicks:::::<%= @question.clicks %></p>
<p>
  <%= @question.body %>
</p>

<h1>Answers</h1>
<hr />
<% answers = @question.answers.desc(:votes, :created_at).page params[:page] %>
<% answers.each do |answer| %>
	<div class="an-answer">
		<a name=<%= answer.id %>></a>
		<% if current_user.voteability==true && ! answer.hasvotedu.include?(current_user.email) && ! answer.hasvotedd.include?(current_user.email) %>
			</p><%= link_to 'Upvote', upvote_answer_path(answer), method: :post %>
			<%= link_to 'Downvote', downvote_answer_path(answer), method: :post %>
			</p>
		<% else -%>	
			<% if answer.hasvotedu.include?(current_user.email) %>
				</p><%= link_to 'Cancel my upvote', downvote_answer_path(answer), method: :post %></p>
			<% end %>
			<% if answer.hasvotedd.include?(current_user.email) %>
				</p><%= link_to 'Cancel my downvote', upvote_answer_path(answer), method: :post %></p>
			<% end %>
		<% end -%>
		<!-- <button>Upvote</button>
		<button>Downvote</button> -->
		  <strong>votes:</strong> <%= answer.votes %>
		  <strong>ANSWERED BY</strong> <%= answer.author.email %>
		<p><%= answer.body %></p>
		<%= link_to 'Add to favorites', add_to_favorite_favorites_path(answer_id: answer.id), data: { confirm: "Are you sure?" }, method: :post %>
		<br /><hr />
	</div>
<% end -%>

<%= paginate answers %>

<%= form_for(Answer.new, url: answer_question_path) do |f| %>
	<%= f.text_area :body %><br /><br />
	<%= f.submit class: "btn btn-default"%>
<% end -%>