config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth"
  resources :users
  resources :favorites do
    collection do
      post "add_to_favorite"
      delete "remove_from_favorite"
    end
  end
  resources :questions do
    collection do
    end
    member do
      post "answer"
    end
  end

  resources :answers do
    member do
      post "upvote"
      post "downvote"
    end
  end

  get "myself" => "users#myself", as: :myself

  root to: "questions#index"

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  field :voteability,        type: Boolean, default: true

  VALID_ROLES = [:admin, :everyone]
  field :role, type: Symbol, default: :everyone
  validates_inclusion_of :role, in: VALID_ROLES

  def admin?
    role == :admin
  end
  
  has_many :questions
  has_many :answers
  has_many :favorites
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def myself
    @user = current_user
    @myself_page_selection = 0
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params.reject { |k, v| v.blank? })
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, User::VALID_ROLES.map { |e| [e.to_s.humanize, e] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/myself.html.erb
<div class="btn-group">
	<% if params[:index].to_i == 0 %>
		<%= link_to 'My Questions', myself_path(index: 0), class: "btn btn-default active" %>
		<%= link_to 'My Answers', myself_path(index: 1), class: "btn btn-default" %>
		<%= link_to 'My Favorites', myself_path(index: 2), class: "btn btn-default" %>
	<% elsif params[:index].to_i == 1 %>
		<%= link_to 'My Questions', myself_path(index: 0), class: "btn btn-default" %>
		<%= link_to 'My Answers', myself_path(index: 1), class: "btn btn-default active" %>
		<%= link_to 'My Favorites', myself_path(index: 2), class: "btn btn-default" %>
	<% elsif params[:index].to_i == 2 %>
		<%= link_to 'My Questions', myself_path(index: 0), class: "btn btn-default" %>
		<%= link_to 'My Answers', myself_path(index: 1), class: "btn btn-default" %>
		<%= link_to 'My Favorites', myself_path(index: 2), class: "btn btn-default active" %>
	<% end -%>
</div>

<%= link_to 'Back to Main Page', root_path, class: "btn btn-default pull-right" %>
<br /><br />

<% if current_user %>
	<div class="pull-right">
		<%= link_to "Sign out", destroy_user_session_path, data: {method: "delete"}, class: "btn btn-default" if current_user %> | 
		<%= link_to "Settings", edit_user_registration_path, class: "btn btn-default" %>
	</div>
<% end -%>

<% if params[:index].to_i == 0 %>
	<h4>My Questions</h4>
	<br />
	<div class="my_questions">
		<% my_questions = @user.questions.desc(:created_at).page params[:my_questions_page] %>
		<% my_questions.each do |question| %>
			<div>
				<h5><strong><%= link_to "#{question.title}", question_path(question) %></strong></h5>
				<p><%= question.body %></p>
				<%= question.answers_count %> answers | <%= question.total_votes %> total votes
				<br /><hr />
			</div>
		<% end -%>
		<%= paginate my_questions, :param_name => "my_questions_page" %>
	</div>
<% elsif params[:index].to_i == 1 %>
	<h4>My Answers</h4>
	<br />
	<div class="my_answers">
		<% my_answers = @user.answers.desc(:created_at).page params[:my_answers_page] %>
		<% my_answers.each do |answer| %>
			<div>
				<h5><strong><%= link_to "#{answer.question.title}", question_path(answer.question) %></strong></h5>
				<%= answer.votes %> votes <br /><br />
				<p><%= link_to "#{answer.body}", question_path(answer.question, page: (answer.question.answers.desc(:votes, :created_at).to_a.index(answer) / Answer.default_per_page + 1), anchor: answer.id) %></p>
				<hr />
			</div>
		<% end -%>
		<%= paginate my_answers, :param_name => "my_answers_page" %>
	</div>
<% elsif params[:index].to_i == 2 %>
	<h4>Favorites</h4>
	<br />
	<div class="favorite">
		<% if @user.favorites.count != 0 %>
			<% favorite_answers = @user.favorites[0].answers.page params[:favorite_page] %>
			<% favorite_answers.each do |answer| %>
				<div>
					<a name=<%= answer.id %>></a>
					<%= link_to 'Destroy', remove_from_favorite_favorites_path(answer_id: answer.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-right" %>
					<h5><strong><%= link_to "#{answer.question.title}", question_path(answer.question) %></strong></h5>
					<%= answer.votes %> votes <br /><br />
					<p><%= link_to "#{answer.body}", question_path(answer.question, page: (answer.question.answers.desc(:votes, :created_at).to_a.index(answer) / Answer.default_per_page + 1), anchor: answer.id) %></p>
					<hr />
				</div>
			<% end -%>
			<%= paginate favorite_answers, :param_name => "favorite_page" %>
		<% end -%>
	</div>
<% end -%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>